language: python

python:
  - "3.6"

install: pip install flake8 pylint typing mypy coverage codecov

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/apocrypha

script:
  # linting
  - pylint --reports=n apocrypha/*py
  - flake8 apocrypha/*.py

  # tests
  - bash test/coverage.sh

  # typing
  - mypy apocrypha/exceptions.py
  - mypy apocrypha/network.py
  - mypy apocrypha/database.py

after_success:
  - codecov
