language: python

python:
  - "3.6"

install: pip install flake8 pylint typing mypy

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/apocrypha

script:
  # linting
  - pylint --reports=n apocrypha/*py
  - flake8 apocrypha/*.py

  # tests
  - python3 test/test_database_unit.py
  - python3 test/test_database_action.py
  - python3 test/test_server.py

  # typing
  - mypy apocrypha/exceptions.py
  - mypy apocrypha/network.py
  - mypy apocrypha/database.py
